### ISSUE TITLE
getessaymaker.com is not available

### ISSUE THREAD

**Issue by IAmJamesHall** [soops/EssayMaker#21]
This looks like a neat project, but when I went to try it out at getessaymaker.com, it appeared that the domain was not registered. Is this just an oversight?

**Comment by ethel-dev** [comment]
On Thu, Mar 22, 2018 at 8:28 AM thatwhichendureth <notifications@github.com>
wrote:

Hey! The domain was registered at one point, but unfortunately I ran out of
money to pay for it. I will push an update tonight using the GitHub domain
and let you know.

> --
- Ethan

**Comment by IAmJamesHall** [comment]
Sorry it took so long to respond. It works great. Thanks!
